# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            # conda create -n test_env python=3.6 anaconda
            # conda activate test_env
            # conda install --file requirements.txt
      Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            conda activate test_env
            flake8 --exclude=venv* --statistics
            pytest -v --cov='./'
