# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    machine: true

    working_directory: ~/repo

    steps:
      # Step 0 : Set nb_conda
      - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      - bash Miniconda3-latest-Linux-x86_64.sh
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            conda create -n tf
            conda activate tf
            while read requirement; do conda install --yes $requirement; done < requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            conda activate tf
            flake8 --statistics
            pytest -v --cov='./'
